### ISSUE TITLE
Convert `to` methods to be more global

### ISSUE THREAD

**Issue by thecaligarmo** [thecaligarmo/oriented_matroids#12]
Currently we have `to_vector()`, `to_cocircuit()` etc which constructs a new oriented matroid of the appropriate type. (ie `to_vector()` returns an OM using the vector axioms). As the number of axioms will grow, instead we should have some method (maybe `change_type`?) which will take in the "type" you want to convert to and will automatically convert to the type you want. For example, if you have `change_type('vector')` then it will give you an OM using the vector axioms.

**Comment by lizzyflight** [comment]
Changing these functions into one larger function `change_type` works for only changing a vector oriented matroid into a circuit oriented matroid as any other combination results in an ` ImplementationError ` due to the functions `circuits()`, `vectors()` & `covectors()` not being implemented yet.
