### ISSUE TITLE
Signed subsets confused with different object?

### ISSUE THREAD

**Issue by tete4761** [thecaligarmo/oriented_matroids#13]
It seems to me that every time I try to input a list of circuits as signed subsets and obtain the OM from it I get the following issue:

_If one of the circuits is of the form ((a1,a2,...,an),(x)), i.e. one of the signed subsets of a circuit has only one element, the code breaks and returns the error **TypeError: 'sage.rings.integer.Integer' object is not iterable**_

An example would be:

```sage: G = [ ((1,5),(2,6)) , ((2,6),(1,5)) , ((2,5),(3,4)) , ((3,4),(2,5)) , ((1,3),(2)) ]```
```sage: N = OrientedMatroid(G,key='circuit')```

This returns the error above. However if our input is this instead:

```sage: H = [ ((1,5),(2,6)) , ((2,6),(1,5)) , ((2,5),(3,4)) , ((3,4),(2,5))  ]```
```sage: H = OrientedMatroid(G,key='circuit')```

The error does not occur anymore

**Comment by thecaligarmo** [comment]
That's because in python `(1)` is just the integer `1`. In this case you want a tuple with just 1 element and so you need to do `(1,)` with the comma after the 1.

**Comment by tete4761** [comment]
Thanks, I will try the examples keeping this in mind.
