### ISSUE TITLE
Cocircuits & covectors implementation

### ISSUE THREAD

**Issue by lizzyflight** [thecaligarmo/oriented_matroids#18]
After testing the cocircuits() function in the abstract_oriented_matroid.py file it returns a NotImplementedError instead of returning the cocircuits of an oriented matroid. So we need to work towards implementing this so that it will return the cocircuits. A similar problem occurs with vector and covector oriented matroids when trying to call vectors() and covectors() with the opposite oriented matroid

**Comment by tete4761** [comment]
All of the above are now implemented.

**Comment by tete4761** [comment]
All of the above are now implemented.
