### ISSUE TITLE
clarify Sage compatibility and what's "not working"

### ISSUE THREAD

**Issue by dimpase** [thecaligarmo/oriented_matroids#23]
As I wrote on [sage-devel](https://groups.google.com/g/sage-devel/c/6knhGwQLAkg/m/TK2cyJJFAQAJ), the package installs fine with a recent Sage 10.2.rcX, and passes tests.

**Comment by thecaligarmo** [comment]
@dimpase Sorry for delay on this. I'll also respond in the email thread, but the beta version for this is now ready. The "not working" part was that some components were returning mathematically incorrect data. So although all the tests and structure was "working", it was not accurate. Me and a few students worked on fixing the bugs and it should be ok now. Let me know if there's any questions =)

**Comment by thecaligarmo** [comment]
I think both of these are done. I added clarification that this works for 10.0, 10.1 and 10.2. In addition to specifying what "doesn't work" (aka, nothing anymore as it's currently in beta).
