### ISSUE TITLE
Modernize python package data (use pyproject.toml)

### ISSUE THREAD

**Issue by mkoeppe** [thecaligarmo/oriented_matroids#27]
In particular, `setup_requires` is no longer a thing. Build dependencies should be declared in pyproject.toml

(For preparing https://github.com/dimpase/primecountpy/pull/12, I found https://pdm-project.org/latest/ to be a useful tool. `pdm init` creates a useful draft of the additions to pyproject.toml; just delete everything pdm-specific afterwards.)

**Comment by thecaligarmo** [comment]
Added the desired changes. Will be pushed to master shortly.
