### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by lizzyflight** [thecaligarmo/oriented_matroids#3]
Examples need fixing as most/all give either an error or not what they are meant to. Also some names need changing for them

**Comment by lizzyflight** [comment]
first example in the constructor.py :
sage: from oriented_matroids import OrientedMatroid

        sage: A = hyperplane_arrangements.braid(3)
        sage: M = OrientedMatroid(A); M

gives an error in line 209. The same thing happens when OrientedMatroid with other inputs

**Comment by thecaligarmo** [comment]
The useful information for this looks to be importing: https://docs.python.org/3/reference/import.html In particular, for us we'll want package relative imports: https://docs.python.org/3/reference/import.html#package-relative-imports

**Comment by tete4761** [comment]
I tried examples in section 1.1 for the OM M0 and the example with the cube in section 3.1 for the Circuit OM and both return errors where they should not. E.g for the cube OM in 3.1 I get error that ground sets must be the same.

sage: C = [ ((1,4),(2,3)) , ((2,3),(1,4)) , ((1,6),(2,5)) , ((2,5),(1,6)) , ((1,8),(2,7)) , ((2,7),(1,8)) , ((1,7),(3,5)) , ((3,5),(1,7)) , ((1,8),(3,6)) , ((3,6),(1,8
....: )) , ((1,8),(4,5)) , ((4,5),(1,8)) , ((2,7),(3,6)) , ((3,6),(2,7)) , ((2,7),(4,5)) , ((4,5),(2,7)) , ((2,8),(4,6)) , ((4,6),(2,8)) , ((3,6),(4,5)) , ((4,5),(3,6)
....: ) , ((3,8),(4,7)) , ((4,7),(3,8)) , ((5,8),(6,7)) , ((6,7),(5,8)) , ((1,8),(2,3,5)) , ((2,3,5),(1,8)) , ((1,4,6),(2,7)) , ((2,7),(1,4,6)) , ((1,4,7),(3,6)) , ((3
....: ,6),(1,4,7)) , ((1,6,7),(4,5)) , ((4,5),(1,6,7)) , ((1,8),(4,6,7)) , ((2,3,8),(4,5)) , ((4,5),(2,3,8)) , ((2,5,8),(3,6)) , ((3,6),(2,5,8)) , ((2,7),(3,5,8)) , ((
....: 3,5,8),(2,7)) ]
sage: M = OrientedMatroid(C,key='circuit')
